#! /bin/bash
# /etc/init.d/garagepy

if [[ `whoami` != "root" ]]; then
	echo "You must run this as root"
	exit 1
fi

#where should the PID of the shell forked process be put?
PID_FILE="/tmp/garagepy.pid"

grpy_stop() {
   echo "Stopping Garage-RPy Website"
   kill -9 `cat $PID_FILE`
   rm -fr $PID_FILE
}

grpy_start() {
  echo "Starting Garage-RPy Website & Control"
  cherrypy-garagepy.py -p $PID_FILE &> /dev/null &
}

cd PATH_TO_GRPY_SOURCE || exit 1

case "$1" in
  restart)
    grpy_stop
    grpy_start
  ;;
	start)
    grpy_start
	;;
	stop)
    grpy_stop
	;;
	*)
		echo "Usage: /etc/init.d/garagepy {start|stop}"
		exit 1
	;;
esac

exit 0
